### ISSUE TITLE
Webpack dev server not recognizing https in OSX/Linux

### ISSUE THREAD

**Issue by mikehedman** [nemanjam/mern-boilerplate#1]
When I start up the client server in dev, it loads http://localhost:3000, not https as expected.
And then trying to navigate to the https address also does not work.

This can be fixed by changing the start command in package.json from
`    "start": "set HTTPS=true&&react-scripts start",`
to
`    "start": "HTTPS=true react-scripts start",`
But, now I see that the first flavor is correct for Windows, the second for Mac/Linux.

By the way, thanks for this project!  I was up and running with very little trouble!!!

**Comment by nemanjam** [comment]
Correct. I used Windows for development environment. I am glad to hear you found it useful.
