### ISSUE TITLE
Quick Setup

### ISSUE THREAD

**Issue by Kadolini** [nemanjam/mern-boilerplate#23]
Hi, i just tried to run this quickly without any changes so far.. i followed the instructions.
with postman server is ok but i think client get rejected somehow by the server.

Request failed with status code 404 => everytime i try with the client side. Any thoughts?

**Comment by nemanjam** [comment]
Is your client requesting `https` routes? This is for Windows.

```json
  "scripts": {
    "start": "set HTTPS=true&&react-scripts start",
     ...
  },
```
If not you can try to add this in `client/package.json`.

```json
"proxy": "https://localhost:5000",
```

Let me know how it works.

**Comment by Kadolini** [comment]
Adding the proxy option inside `client/package.json` helped me finding the problem.
Inside `server/.env` the default port is 80 i changed it with 5000 and it worked. This is why i couldn't reach the server with my client

thanks for the help

**Comment by nemanjam** [comment]
Yes, development and production env vars should be spited and separated.

**Comment by makethisbuildthat** [comment]
I followed the above suggestions but still getting:

Proxy error: Could not proxy request /api/messages from localhost:3000 to https://localhost:5000 (ECONNREFUSED)

Any suggestions?
